orvsd_central/models.py

moodle_tokens field now plural

---

docs/source/installation_instructions.rst

add docs for configuration

---

docs/source/workflow.rst

Docs for requirements

---

docs/source/testing.rst

Testing docs

---

manage.py
orvsd_central/__init__.py
tasks.py
wsgi.py

Cleaner app creation
fixes #127

Remove setup_app

---

manage.py
orvsd_central/models.py
orvsd_central/util.py

Gather siteinfo util function and manage.py command
I also tried to be as helpful as possible in the log output when moodle is misbehaving.
fixes #34

gather siteinfo

---

orvsd_central/controllers/category.py
orvsd_central/models.py
orvsd_central/util.py

Fixes #132 
Also adds some functions to the Site model to make the handling of tokens much easier

install_course moodle_tokens

---

migrations/versions/49e0d0a0a952_adminemail_to_adminlist.py
orvsd_central/controllers/category.py
orvsd_central/models.py
orvsd_central/static/js/report.js
orvsd_central/templates/school.html
orvsd_central/util.py

Store an Adminlist in SiteDetail

---

orvsd_central/controllers/category.py

have install_course() use site as a Site object

---

orvsd_central/static/js/report.js
orvsd_central/templates/report.html

Reports page cleanup for prod release

---

manage.py
orvsd_central/controllers/api.py
orvsd_central/controllers/general.py
orvsd_central/controllers/report.py
orvsd_central/database.py
orvsd_central/models.py
orvsd_central/static/js/install_course.js
orvsd_central/static/js/migrate.js
orvsd_central/static/js/report.js
orvsd_central/static/js/update_models.js
orvsd_central/templates/update_courses.html
orvsd_central/util.py

Code cleanup, both python and javascript.

jshint and flake8 cleanup

---

migrations/versions/2bf8713fd2bb_moodle_tokens_default.py

Add a default to moodle_tokens

---

manage.py
orvsd_central/controllers/api.py
orvsd_central/util.py

gather_tokens and gather_siteinfo now both have a first param wanting a single site object
fixes #141

Consistent gather methods

---

orvsd_central/util.py

use isinstance instead of hasattr to detect type

---

orvsd_central/static/css/base.css
orvsd_central/templates/navbar.html

Flash messages are being displayed again. They do not look pretty at the moment though. #53 is an issue already open to deal with styling.
fixes #120

Missing flash messages

---

orvsd_central/controllers/category.py
orvsd_central/controllers/general.py
orvsd_central/static/css/base.css
orvsd_central/templates/navbar.html
orvsd_central/util.py

Flash messages are now categorized and colored.
fixes #53

Color flash messages

---

orvsd_central/util.py

Fixes gather_tokens not working.

Gather tokens fix

---

manage.py

Removes any orphan site details we have. It doesn't look like it *should* affect the current user count, based on how they're being counted.

Remove orphan sites too.

---

orvsd_central/controllers/report.py
orvsd_central/templates/report.html

Added a "Last Updated" field to report.

---

orvsd_central/static/js/report.js
orvsd_central/util.py

Display total/active users for each site on report
